server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ffernandes286@gmail.com
    password: xttgyprimbuagdrd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: billet-api

  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=billet_db;trustCertificate=true
    username: sa
    password: Billet123456!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        hbm2ddl:
          auto: none
    generate-ddl: false

  flyway:
    enabled: true
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=billet_db;trustCertificate=true
    user: sa
    password: Billet123456!

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: Rabbit123!

app-config:
  services:
    donations-api: http://localhost:8081
    authorization-api: http://localhost:8086
    front-end-web: http://localhost:3000

  security:
    jwt:
      username: donor-user
      password: ZG9Bw6fDo28xMjNAIQ
      secret-key: umlUZ92WEn4ROu0OUmV42Np+XMfPfWiHKx7oZNxkcErpON5tsBLxNMZLwaRrQ+c8cyPmt6RgaZ0tW2LZZDVhbQ==
