server:
  port: 8082

spring:
  application:
    name: billet-api
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=master;trustCertificate=true
    username: sa
    password: Billet123456!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        hbm2ddl:
          auto: none
    generate-ddl: false
  flyway:
    enabled: true
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=master;trustCertificate=true
    user: sa
    password: Billet123456!
    schemas: billet