spring:

  datasource:
    url: jdbc:h2:mem:donation_test;MODE=MSSQLServer
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    url: jdbc:h2:mem:donation_test;MODE=MSSQLServer;DB_CLOSE_DELAY=-1
    user: sa
    password:

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: Rabbit123!

app-config:
  rabbit:
    retry-policy:
      initial-interval: 1000
      max-interval: 3000