spring:

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:h2:mem:billet_test;MODE=MSSQLServer
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    url: jdbc:h2:mem:billet_test;MODE=MSSQLServer;DB_CLOSE_DELAY=-1
    user: sa
    password:

app-config:
  services:
    donations-api: http://localhost:8081
    authorization-api: http://localhost:8086

  security:
    jwt:
      username: donor-user
      password: ZG9Bw6fDo28xMjNAIQ
      secret-key: umlUZ92WEn4ROu0OUmV42Np+XMfPfWiHKx7oZNxkcErpON5tsBLxNMZLwaRrQ+c8cyPmt6RgaZ0tW2LZZDVhbQ==