version: "3"
services:
  
  billet-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: billet-db
    environment:
      MSSQL_SA_PASSWORD: "Billet123456!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  creditcard-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: creditcard-db
    environment:
      MSSQL_SA_PASSWORD: "Credt123456!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/data
    ports:
      - 1434:1433

  donations_rabbit:
    image: rabbitmq:3-management
    container_name: donations_rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "Rabbit123!"
    ports:
      - 5672:5672 
      - 25676:25676 
      - 15672:15672

